### ISSUE TITLE
/lib/Delighted not updated on NPM package install

### ISSUE THREAD

**Issue by jonathanpeterwu** [delighted/delighted-node#2]
https://github.com/delighted/delighted-node/commit/fb116d87f68d5fe696b33ba78f224339b611fc8f

Commit isn't being registered on NPM.

**Comment by paton** [comment]
+1 

For some reason require() is not case sensitive on development, but *is* case sensitive in our production environment, which caused our servers to crash

Would love if you could publish this update to NPM!

**Comment by sorentwo** [comment]
Sure thing! Hate to hear that I caused crashes for you. Publishing a patch shortly tonight.

**Comment by paton** [comment]
Awesome, thanks!

**Comment by sorentwo** [comment]
[v1.0.0-beta2](https://github.com/delighted/delighted-node/releases/tag/v1.0.0-beta2) released. Thanks for the nudge.

**Comment by jonathanpeterwu** [comment]
@sorentwo  thanks for the fast turnaround!
