### ISSUE TITLE
Emoji in `delighted_email_subject` returns 500 Internal Server Error

### ISSUE THREAD

**Issue by sators** [delighted/delighted-node#23]
I'm not sure if this is the best place for this issue, but since I'm encountering it in the node project I'll start it here.

When trying to pass an emoji character in the `delighted_email_subject` property of the `delighted.person.create` call, I receive a `DelightedError` of:

```
{
  type: 'GeneralAPIError',
  message: '{"status":500,"error":"Internal Server Error"}'
}
```
Sample code:
```
const params = {
                email: 'test@example.com',
                name: 'Jim User',
                properties: {
                    delighted_email_subject: '🚌 Jim, would you recommend us?'
                }
            }
delighted.person.create(params)
```

Simply removing the emoji character from the subject creates the record and sends the email with no issue.

I should also note that adding emoji's via the Delighted UI to the subject line works without any issue.

**Comment by mkdynamic** [comment]
@sators Thanks for opening this issue. We do not currently have complete support for emoji's in properties unfortunately – we only support emoji's that take 3 bytes (or less) for properties. This is something that we are actively working on, so please stay tuned. I'll post an update to this ticket when full emoji support is available.

**Comment by thierryung** [comment]
@sators, just a quick ping to let you know we have upgraded our emoji supports, and the sample code you posted should now be working as intended. cheers!
