### ISSUE TITLE
Update existing users?

### ISSUE THREAD

**Issue by paton** [delighted/delighted-node#3]
Would it be possible to create a way to the "properties" / tags of an existing users?

**Comment by mkdynamic** [comment]
@paton You cannot do this currently, but it's definitely on our roadmap for the API. Are you wanting to update the properties and tags only on existing responses? Do you want to update properties on scheduled but not-yet-responded survey requests? Would be great to hear more about your use case so we can ensure the API accommodates what you're trying to achieve.

**Comment by paton** [comment]
Awesome.. basically we ran delighted.person.create() and send out surveys to our whole userbase, but

**Comment by paton** [comment]
Awesome.. basically we ran delighted.person.create() for all of our userbase (inactive users, freemium users, and paying users), and are getting a bunch of responses, but would like to segment them by inactive users, freemium users, and paid users. But we didn't submit these properties when we created the user in Delighted.

So would be super awesome to go back and add tags to them.

**Comment by mkdynamic** [comment]
@paton Got it, that makes total sense. If you shoot me an email at mark [at] delighted.com with your account name, I can help tag/update these properties for you until we have support for this in the API.

**Comment by rayrutjes** [comment]
Any news on this?

**Comment by mkdynamic** [comment]
@rayrutjes Yes! We do have an undocumented API endpoint for updating properties on responses -- can you email help@delighted.com and we can share usage instructions with you.
